services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sql,1433;Database=SkiNet;User Id=sa;Password=Password@1;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
    restart: always
    ports:
      - "5001:80"
    depends_on:
      - sql
      - redis
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - api
volumes:
  sql-data:
  redis-data:
